version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build
      - echo Build finished on `date`
artifacts:
  files:
    - build/libs/demo-0.0.1.jar
  discard-paths: yes
